### ISSUE TITLE
Wrong link for GDE profile

### ISSUE THREAD

**Issue by AlexV525** [wasabeef/wasabeef#1]
Hi Daichi @wasabeef,

Apparently, your profile link is incorrect and cannot be redirected to your profile.
https://github.com/wasabeef/wasabeef/blob/ca01c923569bd5da626fd07ac1860f09ac49e820/README.md?plain=1#L4

It should be `profile-daichi-furiya`.

Regards.

**Comment by wasabeef** [comment]
@AlexV525 Thank you!!
